notifications:
  hipchat:
    rooms:
      secure: MpvHe3jcw/L9yoQYwC3QU5HhEalxHAC88AXbA1UdWG/F3KSMhlZEoRQrU34C4schqE4Ivj93ffsN0u5LcOwjVRhhvA5s3sNP+1tNLnpN5IDDLhb6mGSP9J3erE8GDbIWMG6HizHnz8nKmPw0ugvMCEvxNTePfLmR9uD31zp4IEo=
addons:
  sauce_connect: true
language: node_js
node_js:
- 0.1
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- gulp --node-server --angular-mock-backend &
- sleep 3
script:
- gulp test
- gulp send-stats-to-coveralls
- npm run protractor
before_deploy:
- gulp release --version=build-$TRAVIS_COMMIT
- cd build
- mkdir -p V3/travis
- mv *.tar.gz V3/travis/
deploy:
  - provider: heroku
    api_key:
      secure: XeBcMSubQ+kDtk7B93iJy5HCvXTxp708hUtn9RfjKtNjOyTOha25xZ3lRnYqrhgAOlTY7kieu8QtI4KOZmiRy3U1NwIardvUU44I4f9Q4DDJRGGrPyd61WZwyuAiPWUrePGadZJW2kSuxRXyD3QNm8mBr2njcQp9ln9TpS/57S4=
    app:
      master: ushahidi-platform-master
      release: ushahidi-platform-release
    on:
      repo: ushahidi/platform-client
      branch:
      - master
      - release
  - provider: cloudfiles
    username: ushahidipro
    api_key:
      secure: HO/RdowTebdxfEg9a7B3jEMri6OWk6Oi42v/P1A+k1FXv6A6EvpUB7r7KvH6gy9ByhB152RxelywKyx2BNZCFLHZhnXyoc0UoMt/cBe/pYgLu/FgVFFHTLepEDwugAn/etlZDgnT+dYvPdEgKbUTcl6TKHN8dwKhVpRLi/fBqCI=
    region: DFW
    container: ushahidi-downloads
    skip_cleanup: true
    on:
      repo: ushahidi/platform-client
      all_branches: true

